// <auto-generated />
using System;
using Csharp_Coal.App.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Csharp_Coal.Migrations
{
    [DbContext(typeof(CoalDbContext))]
    partial class CoalDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Csharp_Coal.App.Context.CoalDbContext+Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Carbon")
                        .HasColumnType("integer");

                    b.Property<string>("Heat")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("SizeCoalId")
                        .HasColumnType("integer");

                    b.Property<int>("Volatiles")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SizeCoalId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Carbon = 70,
                            Heat = "6500-7500",
                            Name = "Длиннопламенный",
                            Volatiles = 50
                        },
                        new
                        {
                            Id = 2,
                            Carbon = 65,
                            Heat = "4500-5500",
                            Name = "Бурый",
                            Volatiles = 45
                        });
                });

            modelBuilder.Entity("Csharp_Coal.App.Context.CoalDbContext+CategorySize", b =>
                {
                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<int>("SizeCoalId")
                        .HasColumnType("integer");

                    b.HasKey("CategoryId", "SizeCoalId");

                    b.HasIndex("SizeCoalId");

                    b.ToTable("CategorySizes");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            SizeCoalId = 1
                        },
                        new
                        {
                            CategoryId = 1,
                            SizeCoalId = 2
                        },
                        new
                        {
                            CategoryId = 2,
                            SizeCoalId = 1
                        },
                        new
                        {
                            CategoryId = 2,
                            SizeCoalId = 2
                        });
                });

            modelBuilder.Entity("Csharp_Coal.App.Context.CoalDbContext+SizeCoal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SizeCoals");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Крупный",
                            Size = "более 100мм"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Рядовой",
                            Size = "не имеет ограничений"
                        });
                });

            modelBuilder.Entity("Csharp_Coal.App.Context.CoalDbContext+Category", b =>
                {
                    b.HasOne("Csharp_Coal.App.Context.CoalDbContext+SizeCoal", null)
                        .WithMany("Categories")
                        .HasForeignKey("SizeCoalId");
                });

            modelBuilder.Entity("Csharp_Coal.App.Context.CoalDbContext+CategorySize", b =>
                {
                    b.HasOne("Csharp_Coal.App.Context.CoalDbContext+Category", "Category")
                        .WithMany("CategorySizes")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Csharp_Coal.App.Context.CoalDbContext+SizeCoal", "SizeCoal")
                        .WithMany()
                        .HasForeignKey("SizeCoalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("SizeCoal");
                });

            modelBuilder.Entity("Csharp_Coal.App.Context.CoalDbContext+Category", b =>
                {
                    b.Navigation("CategorySizes");
                });

            modelBuilder.Entity("Csharp_Coal.App.Context.CoalDbContext+SizeCoal", b =>
                {
                    b.Navigation("Categories");
                });
#pragma warning restore 612, 618
        }
    }
}
